---
- hosts: all
  remote_user: root
  vars:
    compose_directory: /data/pandorabox.io
  tasks:
    - name: Checkout git master
      ansible.builtin.git:
        repo: https://github.com/pandorabox-io/pandorabox.io
        dest: "{{ compose_directory }}"
        single_branch: yes
        force: yes
        version: master

    - name: Template minetest config
      template:
        src: "minetest.conf"
        dest: "{{compose_directory}}/data/minetest/minetest.conf"

    - name: Template matterbridge config
      template:
        src: "config/matterbridge.toml"
        dest: "{{compose_directory}}/config/matterbridge.toml"

    - name: Template test matterbridge config
      template:
        src: "config/matterbridge.test.toml"
        dest: "{{compose_directory}}/config/matterbridge.test.toml"

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: "{{ compose_directory }}"
        pull: yes
        build: yes
        remove_orphans: yes

    - name: Reload nginx config
      shell:
        cmd: "docker-compose exec -T nginx nginx -s reload"
        chdir: "{{ compose_directory }}"
