[irc]
[irc.Libera]
Server="irc.libera.chat:6667"
Nick="pandorabot"
Password="{{irc_password}}"
RemoteNickFormat="[{BRIDGE}] <{NICK}> "
ColorNicks=true

[discord]
[discord.Discord]
Token="{{discord_token}}"
Server="513329453741637637"
RemoteNickFormat="[{BRIDGE}] <{NICK}> "
UseUserName=true
AllowMention=["users"]

[api.minetest]
BindAddress="0.0.0.0:4242"
Token="{{matterbridge_token}}"
Buffer=1000
RemoteNickFormat="[{BRIDGE}] {NICK}"

[api.bot]
BindAddress="0.0.0.0:4243"
Token="{{matterbridge_bot_token}}"
Buffer=1000
RemoteNickFormat="[{BRIDGE}] {NICK}"

[[gateway]]
name="main"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#pandorabox"
[[gateway.inout]]
account = "discord.Discord"
channel="main"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="audit"
enable=true
[[gateway.inout]]
account = "discord.Discord"
channel="audit"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="mod"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#pandorabox-mod"
[[gateway.inout]]
account = "discord.Discord"
channel="mod"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="de"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#pandorabox-de"
[[gateway.inout]]
account = "discord.Discord"
channel="de"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="en"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#pandorabox-en"
[[gateway.inout]]
account = "discord.Discord"
channel="en"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="fr"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#pandorabox-offtopic"
[[gateway.inout]]
account = "discord.Discord"
channel="offtopic"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="es"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#pandorabox-es"
[[gateway.inout]]
account = "discord.Discord"
channel="es"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="lag"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#pandorabox-lag"
[[gateway.inout]]
account = "discord.Discord"
channel="lag"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="vote"
enable=true
[[gateway.inout]]
account = "discord.Discord"
channel="vote"
[[gateway.inout]]
account="api.minetest"
channel="api"
[[gateway.inout]]
account="api.bot"
channel="api"

[[gateway]]
name="offtopic"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#pandorabox-offtopic"
[[gateway.inout]]
account = "discord.Discord"
channel="offtopic"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="ru"
enable=true
[[gateway.inout]]
account = "discord.Discord"
channel="ru"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="nsfw"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#pandorabox-nsfw"
[[gateway.inout]]
account = "discord.Discord"
channel="nsfw"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="grounded"
enable=true
[[gateway.inout]]
account = "discord.Discord"
channel="grounded"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="bot"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#pandorabox-bot"
[[gateway.inout]]
account = "discord.Discord"
channel="bot"
[[gateway.inout]]
account="api.minetest"
channel="api"
[[gateway.inout]]
account="api.bot"
channel="api"

[[gateway]]
name="events"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#pandorabox-events"
[[gateway.inout]]
account = "discord.Discord"
channel="events-chat"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="ideas"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#pandorabox-ideas"
[[gateway.inout]]
account = "discord.Discord"
channel="💡ideas"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="fun"
enable=true
[[gateway.inout]]
account = "discord.Discord"
channel="fun"
[[gateway.inout]]
account="api.minetest"
channel="api"

[[gateway]]
name="reports"
enable=true
[[gateway.inout]]
account = "discord.Discord"
channel="reports"
[[gateway.inout]]
account="api.minetest"
channel="api"
