[irc]
[irc.Libera]
Server="irc.libera.chat:6667"
Nick="pandorabot-test"
RemoteNickFormat="[{BRIDGE}] <{NICK}> "
ColorNicks=true
JoinDelay=2000

[discord]
[discord.Discord]
Token="{{discord_test_token}}"
Server="513329453741637637"
RemoteNickFormat="[{BRIDGE}] <{NICK}> "
UseUserName=true
AllowMention=["users"]

[api.minetest]
BindAddress="0.0.0.0:4242"
Token="{{matterbridge_token}}"
Buffer=1000
RemoteNickFormat="[{BRIDGE}] {NICK}"

[[gateway]]
name="main"
enable=true
[[gateway.inout]]
account="irc.Libera"
channel="#pandorabox-test"
[[gateway.inout]]
account = "discord.Discord"
channel="pandorabox-test"
[[gateway.inout]]
account="api.minetest"
channel="api"
